"""Human-in-the-loop review actions on AI drafts: approve, edit, regenerate,
manual, send. AI NEVER auto-sends; this is the human gate."""
from __future__ import annotations

import json

from fastapi import APIRouter, Depends, HTTPException, Request
from sqlalchemy.orm import Session

from app.core.config import settings
from app.core.guardrails import ValidationCode
from app.core.logging import logger
from app.db.session import get_db
from app.models.audit_log import AuditLog
from app.models.brand import Brand
from app.models.conversation import Conversation
from app.models.message import Message
from app.schemas.schemas import ManualReplyCreate, ReviewDecision
from app.services import vector_store
from app.services.llm_service import complete
from app.services.prompt_builder import build_messages, FALLBACK_SENTENCE
from app.services.reranker import rerank

router = APIRouter()


def _msg_or_404(db: Session, message_id: str) -> Message:
    m = db.get(Message, message_id)
    if not m:
        raise HTTPException(404, "Message not found")
    return m


def _conv_or_404(db: Session, conv_id: str) -> Conversation:
    c = db.get(Conversation, conv_id)
    if not c:
        raise HTTPException(404, "Conversation not found")
    return c


@router.get("")
def list_pending(db: Session = Depends(get_db)):
    msgs = (db.query(Message).filter(Message.role == "agent",
                                     Message.status.in_(["pending_review", "regenerated"]))
            .order_by(Message.created_at.desc()).limit(100).all())
    out = []
    for m in msgs:
        brand = db.get(Brand, m.brand_id)
        d = m.to_dict()
        d["brand_name"] = brand.name if brand else ""
        out.append(d)
    return out


@router.post("/{message_id}/decide")
async def decide(message_id: str, payload: ReviewDecision, request: Request,
                 db: Session = Depends(get_db)):
    record = _msg_or_404(db, message_id)
    brand = db.get(Brand, record.brand_id)
    request_id = getattr(request.state, "request_id", "unknown")
    db.add(AuditLog(actor_user_id="agent", entity_type="message", entity_id=record.id,
                    action=f"review_{payload.action}", detail=payload.human_note or "",
                    request_id=request_id))

    # retrieve the originating customer message from the same conversation
    customer_msg = (db.query(Message).filter(Message.conversation_id == record.conversation_id,
                                             Message.role == "customer")
                    .order_by(Message.created_at).first())

    if payload.action == "approve":
        record.status = "approved"
        record.final_text = record.draft_text
        record.human_note = payload.human_note or "approved by human"
    elif payload.action == "edit":
        if not payload.final_text:
            raise HTTPException(400, "final_text required for edit")
        record.status = "edited"
        record.final_text = payload.final_text
        record.human_note = payload.human_note or "edited by human"
    elif payload.action == "regenerate":
        query = customer_msg.content if customer_msg else ""
        ctx = vector_store.query(brand=brand.name, query_text=query, top_k=settings.top_k)
        ctx = rerank(query, ctx, top_n=settings.top_k)
        messages = build_messages(brand.name, query, ctx)
        try:
            new_draft = await complete(messages)
        except RuntimeError:
            new_draft = FALLBACK_SENTENCE
        record.status = "regenerated"
        record.draft_text = new_draft
        record.final_text = new_draft
        record.context_sources = json.dumps([{"source_url": c.get("source", ""),
                                              "score": round(float(c.get("rerank_score", c.get("score", 0))), 4)}
                                             for c in ctx] or [])
        record.human_note = payload.human_note or "regenerated by human"
    elif payload.action == "manual":
        if not payload.final_text:
            raise HTTPException(400, "final_text required for manual")
        record.status = "manual"
        record.final_text = payload.final_text
        record.human_note = payload.human_note or "manual reply by agent"
        record.validation_code = ValidationCode.UNGROUNDED.value
    elif payload.action == "send":
        record.status = "sent"
        record.final_text = record.final_text or record.draft_text
        record.human_note = payload.human_note or "sent"
        logger.info("reply sent id=%s conv=%s brand=%s request_id=%s",
                    record.id, record.conversation_id, brand.name if brand else "", request_id)
    else:
        raise HTTPException(400, "unknown action")

    db.commit()
    db.refresh(record)
    return record.to_dict()


@router.post("/manual")
def manual_reply(payload: ManualReplyCreate, db: Session = Depends(get_db)):
    conv = _conv_or_404(db, payload.conversation_id)
    record = Message(
        conversation_id=conv.id,
        brand_id=payload.brand_id,
        role="agent",
        content="",
        draft_text=payload.text,
        final_text=payload.text,
        status="manual",
        confidence=0.0,
        validation_code=ValidationCode.UNGROUNDED.value,
        human_note=payload.human_note or "manual reply",
    )
    db.add(record)
    db.commit()
    db.refresh(record)
    return record.to_dict()